### ISSUE TITLE
HR should be able to create training programs

### ISSUE THREAD

**Issue by kimberly-bird** [raving-remoras/bangazon-workflow#10]
## Acceptance Criteria

**Given** the user is viewing all training programs
**When** the user clicks the Create New link
**Then** the user should be presented with a form in which the following information can be entered

1. Name
1. Title
1. Start day
1. End day
1. Maximum number of attendees

## Testing Criteria

* Your test suite must verify that the content of the responses contain all required input fields, where a form is requested.
* Your test suite must verify that when a POST operation is performed to the corresponding URL, then a successful response is received. Status code must be 200.

**Comment by kellymorin** [comment]
Approved and merged into master 1/29
