### ISSUE TITLE
HR should be able to edit training program details

### ISSUE THREAD

**Issue by kimberly-bird** [raving-remoras/bangazon-workflow#11]
## Acceptance Criteria

**Given** user is viewing the details of a training program
**When** the user clicks on the edit link
**Then** the user should be presented with a form that allows the user to edit any property of the training program **unless** the training program has already taken place

## Testing Criteria

* Your test suite must verify that the content of the responses contain all required input fields, where appropriate.
* Your test suite must verify that when a PUT operation is performed to the corresponding URL, then a successful response is received. Status code must be 200.

**Comment by kellymorin** [comment]
approved and merged 1/30
