### ISSUE TITLE
HR should be able to view employee details

### ISSUE THREAD

**Issue by kimberly-bird** [raving-remoras/bangazon-workflow#4]
## Acceptance Criteria

**Given** a user is viewing the employee list
**When** the user clicks on an individual employee
**Then** the user should be shown a detail view of that employee, and it must contain the following information

1. First name and last name
1. Department
1. Currently assigned computer
1. Training programs they have attended, or plan on attending

## Testing Criteria

* Your test suite must verify that the content of the response has all of the expected values of the employee - name, department, computer, and training programs.

**Comment by kellymorin** [comment]
Dependent on Issue #2

**Comment by kellymorin** [comment]
Approved and merged 1/29
