### ISSUE TITLE
HR should be able to create a department

### ISSUE THREAD

**Issue by kimberly-bird** [raving-remoras/bangazon-workflow#7]
## Acceptance Criteria

**Given** user is viewing all departments
**When** user clicks on the Create New link
**Then** a form should be presented in which the new department name can be entered

## Testing Criteria

* Your test suite must verify that the content of the response has the required input fields.
* Your test suite must verify that when a POST operation is performed to the corresponding URL, then a successful response is received (i.e. status code must be 200)

**Comment by kellymorin** [comment]
Dependent on Ticket #6
