### ISSUE TITLE
HR should be able to view department details

### ISSUE THREAD

**Issue by kimberly-bird** [raving-remoras/bangazon-workflow#8]
## Acceptance Criteria

**Given** user is viewing list of departments
**When** user clicks on a department
**Then** a view should be presented with the department name as a header
**And** a list of employees currently assigned to that department should be listed

## Testing Criteria

* Your test suite must verify that all labels and values are in the response for the requested department

**Comment by kellymorin** [comment]
Dependent on Ticket #6
